% Random walk coordinate generator

% Simulation paramters
xL = -0.05;
xH = 0.05;
yL = -0.05;
yH = 0.05;

xEnd = 1000;
xStep = 3; % um
% lets say each time step is 0.1 sec
% With the speed of bacteria of about 10um/s, in each time step
% we will move about 1um.
yStep = xStep;
tStep = 0.1; % s
tEnd = 6000;  % s
tPoints = tEnd/tStep;
xyCoords = zeros(tPoints,3);
i = 2;  % time index (integer)

% Initial conditions
x0 = 500; % um
y0 = 500; % um

% rand(1,2) means random number [0,1] in (1,2) matrix
% 1,2 refers to matrix dimensions, not to the segment.

% Random number from -1,1 is generated by
% r = (-1) + (1 - (-1)).*rand(1)

% Do the first entry outside of the loop
%xyCoords(1,:) = [0 round((randi(2,1,2) - 1.5))*xStep];

xyCoords(1,:) = [0 x0 y0];


for t = tStep:tStep:tEnd
    randomCoords = round2(xyCoords(i-1,2:3) + ...
        round((randi(2,1,2) - 1.5))*xStep, xStep);
    xyCoords(i,:) = [t mod(randomCoords,xEnd)];
    % Modulo operation is for periodic boundary conditions
    i = i + 1;
end

xCoords = xyCoords(:,[1 2]);
yCoords = xyCoords(:,[1 3]);

% Write results to files so we can import them to COMSOL
dlmwrite('Random walk, x vs t, xyStep3.txt', xCoords, 'delimiter', '\t');
dlmwrite('Random walk, y vs t, xyStep3.txt', yCoords, 'delimiter', '\t');